version: '3'
services:
  nginx:
    image: nginx:alpine
    hostname: 'nginx'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/proxy.conf:/etc/nginx/proxy.conf
    ports:
      - '80:80'
    depends_on:
      - aspapp
    restart: always

  aspapp:
    build: ./ao-docker-tech-test
    ports:
      - '80'
    restart: always
